import merge from 'deepmerge';
import { DefaultTheme } from 'styled-components';

import * as tokens from '../tokens/tokens';

export const defaultTheme: DefaultTheme = {
    breakpoints: [
        tokens.kdsBreakpointSmall,
        tokens.kdsBreakpointMedium,
        tokens.kdsBreakpointLarge,
        tokens.kdsBreakpointXlarge,
    ],
    space: [
        tokens.kdsSpacing0,
        tokens.kdsSpacing1,
        tokens.kdsSpacing2,
        tokens.kdsSpacing3,
        tokens.kdsSpacing4,
        tokens.kdsSpacing5,
        tokens.kdsSpacing6,
        tokens.kdsSpacing7,
        tokens.kdsSpacing8,
        tokens.kdsSpacing9,
        tokens.kdsSpacing10,
        tokens.kdsSpacing11,
    ],
    colors: {
        neutral50: tokens.kdsColorNeutral50,
        neutral100: tokens.kdsColorNeutral100,
        neutral200: tokens.kdsColorNeutral200,
        neutral300: tokens.kdsColorNeutral300,
        neutral400: tokens.kdsColorNeutral400,
        neutral500: tokens.kdsColorNeutral500,
        neutral600: tokens.kdsColorNeutral600,
        neutral700: tokens.kdsColorNeutral700,
        neutral800: tokens.kdsColorNeutral800,
        neutral900: tokens.kdsColorNeutral900,
        success: tokens.kdsColorLime500,
        warning: tokens.kdsColorOrange500,
    },
    alert: {
        danger: {
            backgroundColor: '#FEF5E9',
            color: '#FF9A1E',
            colorHover: '#d17300',
        },
        info: {
            backgroundColor: '#EBF9FE',
            color: '#00ADF8',
            colorHover: '#006692',
        },
        success: {
            backgroundColor: '#EBFBF3',
            color: '#00D06A',
            colorHover: '#006a36',
        },
    },
    badge: {
        badgeColor: {
            blue: tokens.kdsColorBlue100,
            lime: tokens.kdsColorLime100,
            magenta: tokens.kdsColorMagenta100,
            neutral: tokens.kdsColorNeutral100,
            orange: tokens.kdsColorOrange100,
            turquoise: tokens.kdsColorTurquoise200,
            yellow: tokens.kdsColorYellow100,
        },
        badgeSize: {
            large: tokens.kdsSpacing2,
            medium: tokens.kdsSpacing2,
            small: tokens.kdsSpacing2,
        },
        color: {
            blue: tokens.kdsColorBlue500,
            lime: tokens.kdsColorLime500,
            magenta: tokens.kdsColorMagenta500,
            neutral: tokens.kdsColorNeutral900,
            orange: tokens.kdsColorOrange400,
            turquoise: tokens.kdsColorTurquoise600,
            yellow: tokens.kdsColorYellow800,
        },
        fontFamily: tokens.kdsFontFamilyBase,
        fontSize: {
            large: tokens.kdsFontSize300,
            medium: tokens.kdsFontSize200,
            small: tokens.kdsFontSize100,
        },
        fontWeight: tokens.kdsFontWeightMedium,
        lineHeight: tokens.kdsLineHeightNone,
    },
    button: {
        small: {
            borderRadius: tokens.kdsBorderRadiusSharp,
            fontSize: tokens.kdsFontSize200,
            fontWeight: tokens.kdsFontWeightBold,
            height: '32px',
            letterSpacing: tokens.kdsLetterSpacingNormal,
            lineHeight: tokens.kdsLineHeightNone,
            paddingLeft: '12px',
            paddingRight: '12px',
        },
        medium: {
            borderRadius: tokens.kdsBorderRadiusSharp,
            fontSize: tokens.kdsFontSize200,
            fontWeight: tokens.kdsFontWeightBold,
            height: '36px',
            letterSpacing: tokens.kdsLetterSpacingNormal,
            lineHeight: tokens.kdsLineHeightNone,
            paddingLeft: '16px',
            paddingRight: '16px',
        },
        large: {
            borderRadius: tokens.kdsBorderRadiusSharp,
            fontSize: tokens.kdsFontSize300,
            fontWeight: tokens.kdsFontWeightBold,
            height: '40px',
            letterSpacing: tokens.kdsLetterSpacingNormal,
            lineHeight: tokens.kdsLineHeightNone,
            paddingLeft: '21px',
            paddingRight: '21px',
        },
        blue: {
            background: tokens.kdsGradientBlue,
            backgroundActive: tokens.kdsColorBlue600,
            border: tokens.kdsColorBlue500,
            boxShadowColor: tokens.kdsColorBlue300,
            color: tokens.kdsColorWhite,
            colorOutline: tokens.kdsColorBlue500,
            colorOutlineActive: tokens.kdsColorWhite,
            colorOutlineHover: tokens.kdsColorWhite,
        },
        magenta: {
            background: tokens.kdsGradientMagenta,
            backgroundActive: tokens.kdsColorMagenta600,
            border: tokens.kdsColorMagenta500,
            boxShadowColor: tokens.kdsColorBlue300,
            color: tokens.kdsColorWhite,
            colorOutline: tokens.kdsColorMagenta500,
            colorOutlineActive: tokens.kdsColorWhite,
            colorOutlineHover: tokens.kdsColorWhite,
        },
        outline: {
            backgroundDisabled: tokens.kdsColorWhite,
            borderDisabled: tokens.kdsColorNeutral200,
            colorDisabled: tokens.kdsColorNeutral300,
        },
        solid: {
            backgroundDisabled: tokens.kdsColorNeutral300,
            borderDisabled: tokens.kdsColorNeutral300,
            colorDisabled: tokens.kdsColorWhite,
        },
        ghost: {
            backgroundDisabled: tokens.kdsColorWhite,
            borderDisabled: tokens.kdsColorTransparent,
            colorDisabled: tokens.kdsColorNeutral300,
            magenta: {
                color: tokens.kdsColorMagenta500,
                colorActive: tokens.kdsColorMagenta600,
                boxShadowColor: tokens.kdsColorMagenta300,
            },
            blue: {
                color: tokens.kdsColorBlue500,
                colorActive: tokens.kdsColorBlue600,
                boxShadowColor: tokens.kdsColorBlue300,
            },
        },
    },
    card: {
        boxShadowNone: tokens.kdsBoxShadowNone,
        boxShadowLevel1: tokens.kdsBoxShadowLevel1,
        boxShadowLevel2: tokens.kdsBoxShadowLevel2,
        boxShadowLevel3: tokens.kdsBoxShadowLevel3,
        paddingSpacing0: tokens.kdsSpacing0,
        paddingSpacing1: tokens.kdsSpacing7,
        paddingSpacing2: tokens.kdsSpacing8,
        paddingSpacing3: tokens.kdsSpacing9,
        paddingSpacing4: tokens.kdsSpacing10,
    },
    checkbox: {
        accentColor: tokens.kdsColorBlue500,
        accentColorDisabled: tokens.kdsColorBlue200,
        backgroundColor: tokens.kdsColorWhite,
        backgroundColorDisabled: tokens.kdsColorNeutral100,
        borderColor: tokens.kdsColorNeutral500,
        borderColorDisabled: tokens.kdsColorNeutral400,
        borderColorHover: tokens.kdsColorNeutral700,
        boxShadowColorFocus: tokens.kdsColorBlue300,
        labelColor: tokens.kdsColorNeutral700,
        labelColorDisabled: tokens.kdsColorNeutral400,
        labelFontSize: {
            medium: tokens.kdsFontSize200,
            large: tokens.kdsFontSize300,
        },
        labelLineHeight: {
            medium: tokens.kdsLineHeight200,
            large: tokens.kdsLineHeight300,
        },
        rippleColor: tokens.kdsColorNeutral100,
    },
    collection: {
        icon: {
            color: tokens.kdsColorNeutral300,
            easing: tokens.kdsEaseOut,
            hoverColor: tokens.kdsColorNeutral400,
        },
        link: {
            easing: tokens.kdsEaseIn,
            hoverColor: tokens.kdsColorNeutral50,
        },
    },
    feedback: {
        backgroundColor: tokens.kdsColorOrange100,
        borderRadius: tokens.kdsBorderRadiusSharp,
        color: tokens.kdsColorOrange500,
        fontFamily: tokens.kdsFontFamilyBase,
        fontSize: tokens.kdsFontSize100,
        fontWeight: tokens.kdsFontWeightMedium,
        lineHeight: tokens.kdsLineHeightTight,
        space: tokens.kdsSpacing2,
    },
    form: {
        boxShadow: tokens.kdsBoxShadowLevel2,
        margin: tokens.kdsSpacingStack4,
        paddingSides: tokens.kdsSpacing8,
        paddingTop: tokens.kdsSpacing7,
    },
    formGroup: {
        breakpoints: {
            small: {
                breakpoint: tokens.kdsBreakpointSmall,
            },
        },
        formgroupHeight: tokens.kdsSize8,
        labelFontSize: tokens.kdsFontSize200,
        labelLineheight: tokens.kdsLineHeightNormal,
        margin: tokens.kdsSpacing2,
        read: {
            margin: tokens.kdsSpacing0,
            padding: tokens.kdsSpacing2,
        },
        small: {
            margin: tokens.kdsSpacing6,
        },
        stacked: {
            margin: tokens.kdsSpacing4,
        },
    },
    formHeader: {
        margin: tokens.kdsSpacingStack7,
    },
    formLabel: {
        asterisk: {
            color: tokens.kdsColorGreen500,
            fontSize: tokens.kdsFontSize300,
            fontWeight: tokens.kdsFontWeightBold,
        },
        color: tokens.kdsColorNeutral700,
        error: {
            color: tokens.kdsColorOrange500,
        },
        fontFamily: tokens.kdsFontFamilyBase,
        fontSize: tokens.kdsFontSize200,
        fontWeight: tokens.kdsFontWeightNormal,
        lineHeight: tokens.kdsLineHeightNormal,
    },
    formLayout: {
        columnSpacing: tokens.kdsSpacing3,
        condensedSpacing: tokens.kdsSpacing1,
    },
    formSection: {
        borderColor: tokens.kdsColorNeutral200,
        formSectionHeader: {
            margin: tokens.kdsSpacingStack6,
        },
        margin: tokens.kdsSpacing7,
        padding: tokens.kdsSpacing6,
    },
    iconButton: {
        default: {
            backgroundColor: tokens.kdsColorTransparent,
            backgroundColorActive: tokens.kdsColorNeutral300,
            backgroundColorFocus: tokens.kdsColorNeutral200,
            backgroundColorHover: tokens.kdsColorNeutral200,
            boxShadowColorFocus: tokens.kdsColorBlue300,
            boxShadowSpreadRadiusFirst: '2px',
            boxShadowSpreadRadiusSecond: '4px',
            color: tokens.kdsColorNeutral400,
            colorDisabled: tokens.kdsColorNeutral300,
            colorFocus: tokens.kdsColorNeutral800,
            colorHover: tokens.kdsColorNeutral800,
        },
        filled: {
            backgroundColor: tokens.kdsColorNeutral200,
            backgroundColorActive: tokens.kdsColorNeutral300,
            backgroundColorFocus: tokens.kdsColorNeutral200,
            backgroundColorHover: tokens.kdsColorNeutral200,
            boxShadowColorFocus: tokens.kdsColorBlue300,
            boxShadowSpreadRadiusFirst: '2px',
            boxShadowSpreadRadiusSecond: '4px',
            color: tokens.kdsColorNeutral800,
            colorDisabled: tokens.kdsColorNeutral300,
            colorFocus: tokens.kdsColorNeutral800,
            colorHover: tokens.kdsColorNeutral900,
        },
        ghost: {
            backgroundColor: tokens.kdsColorTransparent,
            backgroundColorActive: tokens.kdsColorTransparent,
            backgroundColorFocus: tokens.kdsColorTransparent,
            backgroundColorHover: tokens.kdsColorTransparent,
            boxShadowColorFocus: tokens.kdsColorBlue300,
            boxShadowSpreadRadiusFirst: '0px',
            boxShadowSpreadRadiusSecond: '2px',
            color: tokens.kdsColorNeutral400,
            colorDisabled: tokens.kdsColorNeutral300,
            colorFocus: tokens.kdsColorNeutral800,
            colorHover: tokens.kdsColorNeutral800,
        },
        inverse: {
            backgroundColor: tokens.kdsColorTransparent,
            backgroundColorActive: tokens.kdsColorTransparent,
            backgroundColorFocus: tokens.kdsColorTransparent,
            backgroundColorHover: tokens.kdsColorTransparent,
            boxShadowColorFocus: tokens.kdsColorWhite,
            boxShadowSpreadRadiusFirst: '0px',
            boxShadowSpreadRadiusSecond: '2px',
            color: tokens.kdsColorWhite,
            colorDisabled: tokens.kdsColorNeutral300,
            colorFocus: tokens.kdsColorWhite,
            colorHover: tokens.kdsColorWhite,
        },
    },
    iconCircle: {
        backgroundColor: tokens.kdsColorTransparent,
        borderColor: tokens.kdsColorNeutral200,
        accent: {
            blue: tokens.kdsColorBlue500,
            magenta: tokens.kdsColorMagenta500,
        },
    },
    link: {
        blue: {
            color: tokens.kdsColorBlue500,
        },
        fontFamily: tokens.kdsFontFamilyBase,
        magenta: {
            color: tokens.kdsColorMagenta500,
        },
        grey: {
            color: tokens.kdsColorNeutral800,
        },
        lightGrey: {
            color: tokens.kdsColorNeutral500,
        },
    },
    list: {
        listItem: {
            color: tokens.kdsColorNeutral800,
            fontFamily: tokens.kdsFontFamilyBase,
            fontSize: tokens.kdsFontSize300,
            fontWeight: tokens.kdsFontWeightNormal,
            lineHeight: tokens.kdsLineHeightNormal,
            margin: tokens.kdsSpacingStack2,
            marginCondensed: tokens.kdsSpacingStack1,
            marginWide: tokens.kdsSpacingStack3,
            selectedColor: tokens.kdsColorMagenta500,
        },
        margin: tokens.kdsSpacingStack4,
    },
    listRow: {
        margin: tokens.kdsSpacing4,
        padding: {
            large: tokens.kdsSpacing6,
            medium: tokens.kdsSpacing4,
            small: tokens.kdsSpacing3,
        },
    },
    mediaObject: {
        bodySpacing: tokens.kdsSpacing2,
        color: tokens.kdsColorNeutral800,
        paragraphFontSize: tokens.kdsFontSize200,
        stackedSpacing: tokens.kdsSpacing6,
        borderColor: tokens.kdsColorNeutral200,
    },
    menu: {
        backgroundColorFocus: tokens.kdsColorNeutral100,
        backgroundColorFocusDisabled: tokens.kdsColorNeutral100,
        color: tokens.kdsColorNeutral900,
        colorDisabled: tokens.kdsColorNeutral400,
    },
    navDropdown: {
        accentColor: tokens.kdsColorMagenta500,
        color: tokens.kdsColorNeutral900,
        iconBackgroundColor: tokens.kdsColorNeutral200,
        iconColor: tokens.kdsColorNeutral400,
        toggleSubtitleColor: tokens.kdsColorNeutral400,
        toggleTitleColor: tokens.kdsColorNeutral900,
    },
    radio: {
        accentColor: tokens.kdsColorBlue500,
        backgroundColor: tokens.kdsColorWhite,
        backgroundColorDisabled: tokens.kdsColorNeutral100,
        borderColor: tokens.kdsColorNeutral500,
        borderColorDisabled: tokens.kdsColorNeutral400,
        borderColorHover: tokens.kdsColorNeutral700,
        boxShadowColorFocus: tokens.kdsColorBlue300,
        labelColor: tokens.kdsColorNeutral700,
        labelColorDisabled: tokens.kdsColorNeutral400,
        labelFontSize: tokens.kdsFontSize200,
        rippleColor: tokens.kdsColorNeutral100,
    },
    radioButton: {
        accentColor: tokens.kdsColorBlue500,
        backgroundColor: tokens.kdsColorWhite,
        backgroundColorDisabled: tokens.kdsColorNeutral300,
        borderColor: tokens.kdsColorNeutral500,
        borderColorDisabled: tokens.kdsColorNeutral300,
        borderColorHover: tokens.kdsColorNeutral700,
        boxShadowColorFocus: tokens.kdsColorBlue300,
        color: tokens.kdsColorNeutral500,
        colorChecked: tokens.kdsColorWhite,
        colorDisabled: tokens.kdsColorNeutral300,
        colorHover: tokens.kdsColorBlue500,
        fontSize: tokens.kdsFontSize200,
    },
    textField: {
        backgroundColor: tokens.kdsColorTransparent,
        borderColor: tokens.kdsColorNeutral300,
        borderColorFocus: tokens.kdsColorNeutral700,
        borderColorHover: tokens.kdsColorNeutral400,
        borderColorTransparent: tokens.kdsColorTransparent,
        color: tokens.kdsColorNeutral900,
        disabled: {
            borderColor: tokens.kdsColorNeutral300,
            color: tokens.kdsColorNeutral400,
        },
        error: {
            borderColor: tokens.kdsColorOrange500,
            borderColorFocus: tokens.kdsColorOrange600,
            borderColorHover: tokens.kdsColorOrange600,
            color: tokens.kdsColorOrange500,
        },
        fontFamily: tokens.kdsFontFamilyBase,
        fontSize: tokens.kdsFontSize300,
        fontWeight: tokens.kdsFontWeightMedium,
        height: tokens.kdsSize8,
        lineHeight: tokens.kdsLineHeightNormal,
        placeholder: {
            color: tokens.kdsColorNeutral400,
            fontWeight: tokens.kdsFontWeightNormal,
        },
        readOnly: {
            borderColor: tokens.kdsColorTransparent,
        },
    },
    typography: {
        fontFamilyBase: tokens.kdsFontFamilyBase,
        fontWeights: {
            bold: tokens.kdsFontWeightBold,
            medium: tokens.kdsFontWeightMedium,
            normal: tokens.kdsFontWeightNormal,
        },
        fontSize: {
            100: tokens.kdsFontSize100,
            200: tokens.kdsFontSize200,
            300: tokens.kdsFontSize300,
            400: tokens.kdsFontSize400,
            500: tokens.kdsFontSize500,
            600: tokens.kdsFontSize600,
            700: tokens.kdsFontSize700,
            800: tokens.kdsFontSize800,
            900: tokens.kdsFontSize900,
        },
        lineHeight: {
            100: tokens.kdsLineHeight100,
            200: tokens.kdsLineHeight200,
            300: tokens.kdsLineHeight300,
            400: tokens.kdsLineHeight400,
            500: tokens.kdsLineHeight500,
            600: tokens.kdsLineHeight600,
            700: tokens.kdsLineHeight700,
            800: tokens.kdsLineHeight800,
            900: tokens.kdsLineHeight900,
        },
    },
    switch: {
        backgroundColorCircle: tokens.kdsColorNeutral500,
        backgroundColorCircleChecked: tokens.kdsColorBlue500,
        backgroundColorCircleDisabled: tokens.kdsColorNeutral300,
        backgroundColor: tokens.kdsColorWhite,
        backgroundColorDisabled: tokens.kdsColorWhite,
        borderColor: tokens.kdsColorNeutral500,
        borderColorDisabled: tokens.kdsColorNeutral200,
        boxShadowColorFocus: tokens.kdsColorBlue300,
        fontSize: tokens.kdsFontSize200,
        color: tokens.kdsColorNeutral500,
        colorChecked: tokens.kdsColorBlue500,
        colorDisabled: tokens.kdsColorNeutral300,
    },
    inputCheckmark: {
        fontSize: tokens.kdsFontSize300,
        fontFamily: tokens.kdsFontFamilyBase,
        lineHeight: tokens.kdsLineHeightNormal,
        fontWeight: tokens.kdsFontWeightNormal,
        borderColor: tokens.kdsColorNeutral300,
        borderColorHover: tokens.kdsColorNeutral400,
        colorDisabled: tokens.kdsColorNeutral400,
        boxShadow: tokens.kdsBoxShadowLevel3,
        color: tokens.kdsColorNeutral700,
        multiLine: {
            color: tokens.kdsColorNeutral700,
            labelFontWeight: tokens.kdsFontWeightMedium,
            bodyTextColor: tokens.kdsColorNeutral600,
        },
        magenta: {
            backgroundColor: tokens.kdsColorMagenta500,
        },
        blue: {
            backgroundColor: tokens.kdsColorBlue500,
        },
    },
    steps: {
        accentColor: tokens.kdsColorBlue500,
    },
    authCode: {
        danger: {
            color: '#f92549',
        },
        default: {
            color: tokens.kdsColorMagenta500,
        },
        success: {
            color: tokens.kdsColorLime500,
        },
    },
};

export const mijnKsyosTheme: DefaultTheme = merge(defaultTheme, {
    checkbox: {
        accentColor: tokens.kdsColorMagenta500,
        accentColorDisabled: tokens.kdsColorMagenta200,
    },
    radio: {
        accentColor: tokens.kdsColorMagenta500,
        boxShadowColorFocus: tokens.kdsColorMagenta300,
    },
});
