import * as tokens from './tokens';

export const tokenlist = {
    fontWeight: {
        kdsFontWeightNormal: tokens.kdsFontWeightNormal,
        kdsFontWeightMedium: tokens.kdsFontWeightMedium,
        kdsFontWeightBold: tokens.kdsFontWeightBold,
    },
    fontFamily: {
        kdsFontFamilyBase: tokens.kdsFontFamilyBase,
    },
    fontSize: {
        kdsFontSize100: tokens.kdsFontSize100,
        kdsFontSize200: tokens.kdsFontSize200,
        kdsFontSize300: tokens.kdsFontSize300,
        kdsFontSize400: tokens.kdsFontSize400,
        kdsFontSize500: tokens.kdsFontSize500,
        kdsFontSize600: tokens.kdsFontSize600,
        kdsFontSize700: tokens.kdsFontSize700,
        kdsFontSize800: tokens.kdsFontSize800,
        kdsFontSize900: tokens.kdsFontSize900,
    },
    fontStyle: {
        kdsFontStyleNormal: tokens.kdsFontStyleNormal,
        kdsFontStyleItalic: tokens.kdsFontStyleItalic,
    },
    LineHeight: {
        kdsLineHeightNone: tokens.kdsLineHeightNone,
        kdsLineHeightTight: tokens.kdsLineHeightTight,
        kdsLineHeightSnug: tokens.kdsLineHeightSnug,
        kdsLineHeightNormal: tokens.kdsLineHeightNormal,
        kdsLineHeightRelaxed: tokens.kdsLineHeightRelaxed,
        kdsLineHeightLoose: tokens.kdsLineHeightLoose,
    },
    LetterSpacing: {
        kdsLetterSpacingTighter: tokens.kdsLetterSpacingTighter,
        kdsLetterSpacingTight: tokens.kdsLetterSpacingTight,
        kdsLetterSpacingNormal: tokens.kdsLetterSpacingNormal,
        kdsLetterSpacingWide: tokens.kdsLetterSpacingWide,
        kdsLetterSpacingWider: tokens.kdsLetterSpacingWider,
        kdsLetterSpacingWidest: tokens.kdsLetterSpacingWidest,
    },
    Breakpoints: {
        kdsBreakpointSmall: tokens.kdsBreakpointSmall,
        kdsBreakpointMedium: tokens.kdsBreakpointMedium,
        kdsBreakpointLarge: tokens.kdsBreakpointLarge,
        kdsBreakpointXlarge: tokens.kdsBreakpointXlarge,
    },
    Spacing: {
        kdsSpacing0: tokens.kdsSpacing0,
        kdsSpacing1: tokens.kdsSpacing1,
        kdsSpacing2: tokens.kdsSpacing2,
        kdsSpacing3: tokens.kdsSpacing3,
        kdsSpacing4: tokens.kdsSpacing4,
        kdsSpacing5: tokens.kdsSpacing5,
        kdsSpacing6: tokens.kdsSpacing6,
        kdsSpacing7: tokens.kdsSpacing7,
        kdsSpacing8: tokens.kdsSpacing8,
        kdsSpacing9: tokens.kdsSpacing9,
        kdsSpacing10: tokens.kdsSpacing10,
        kdsSpacing11: tokens.kdsSpacing11,
    },
    Stack: {
        kdsSpacingStack0: tokens.kdsSpacingStack0,
        kdsSpacingStack1: tokens.kdsSpacingStack1,
        kdsSpacingStack2: tokens.kdsSpacingStack2,
        kdsSpacingStack3: tokens.kdsSpacingStack3,
        kdsSpacingStack4: tokens.kdsSpacingStack4,
        kdsSpacingStack5: tokens.kdsSpacingStack5,
        kdsSpacingStack6: tokens.kdsSpacingStack6,
        kdsSpacingStack7: tokens.kdsSpacingStack7,
        kdsSpacingStack8: tokens.kdsSpacingStack8,
        kdsSpacingStack9: tokens.kdsSpacingStack9,
        kdsSpacingStack10: tokens.kdsSpacingStack10,
        kdsSpacingStack11: tokens.kdsSpacingStack11,
    },
    Inset: {
        kdsSpacingInset0: tokens.kdsSpacingInset0,
        kdsSpacingInset1: tokens.kdsSpacingInset1,
        kdsSpacingInset2: tokens.kdsSpacingInset2,
        kdsSpacingInset3: tokens.kdsSpacingInset3,
        kdsSpacingInset4: tokens.kdsSpacingInset4,
        kdsSpacingInset5: tokens.kdsSpacingInset5,
        kdsSpacingInset6: tokens.kdsSpacingInset6,
        kdsSpacingInset7: tokens.kdsSpacingInset7,
        kdsSpacingInset8: tokens.kdsSpacingInset8,
        kdsSpacingInset9: tokens.kdsSpacingInset9,
        kdsSpacingInset10: tokens.kdsSpacingInset10,
        kdsSpacingInset11: tokens.kdsSpacingInset11,
    },
    Sizing: {
        kdsSize0: tokens.kdsSize0,
        kdsSize1: tokens.kdsSize1,
        kdsSize2: tokens.kdsSize2,
        kdsSize3: tokens.kdsSize3,
        kdsSize4: tokens.kdsSize4,
        kdsSize5: tokens.kdsSize5,
        kdsSize6: tokens.kdsSize6,
        kdsSize7: tokens.kdsSize7,
        kdsSize8: tokens.kdsSize8,
        kdsSize9: tokens.kdsSize9,
        kdsSize10: tokens.kdsSize10,
        kdsSize11: tokens.kdsSize11,
        kdsSize12: tokens.kdsSize12,
        kdsSize13: tokens.kdsSize13,
    },
    BorderRadius: {
        kdsBorderRadiusSharp: tokens.kdsBorderRadiusSharp,
        kdsBorderRadiusBase: tokens.kdsBorderRadiusBase,
        kdsBorderRadiusFull: tokens.kdsBorderRadiusFull,
    },
    IconSize: {
        kdsIconSizeTiny: tokens.kdsIconSizeTiny,
        kdsIconSizeSmall: tokens.kdsIconSizeSmall,
        kdsIconSizeMedium: tokens.kdsIconSizeMedium,
        kdsIconSizeLarge: tokens.kdsIconSizeLarge,
    },
    Easing: {
        kdsEaseIn: tokens.kdsEaseIn,
        kdsEaseOut: tokens.kdsEaseOut,
        kdsEaseInOut: tokens.kdsEaseInOut,
    },
    Duration: {
        kdsDuration1: tokens.kdsDuration1,
        kdsDuration2: tokens.kdsDuration2,
        kdsDuration3: tokens.kdsDuration3,
        kdsDuration4: tokens.kdsDuration4,
        kdsDuration5: tokens.kdsDuration5,
        kdsDuration6: tokens.kdsDuration6,
    },
    Scrims: {
        kdsScrimLight: tokens.kdsScrimLight,
        kdsScrimDark: tokens.kdsScrimDark,
    },
    BoxShadow: {
        kdsBoxShadowNone: tokens.kdsBoxShadowNone,
        kdsBoxShadowLevel1: tokens.kdsBoxShadowLevel1,
        kdsBoxShadowLevel2: tokens.kdsBoxShadowLevel2,
        kdsBoxShadowLevel3: tokens.kdsBoxShadowLevel3,
    },
    Gradients: {
        kdsGradientMagenta: tokens.kdsGradientMagenta,
        kdsGradientBlue: tokens.kdsGradientBlue,
        kdsGradientOrange: tokens.kdsGradientOrange,
        kdsGradientNeutral: tokens.kdsGradientNeutral,
    },
};
